exclude:
  - node_modules
  - scripts

sass:
  style: compressed

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/arakelian/jekyll-theme-gerbera"

theme: jekyll-theme-gerbera

jekyll_tidy:
    compress_html: true
    ignore_env: development    

markdown: kramdown
highlighter: rouge


title:    Gerbera Theme for Jekyll
tagline:  Gerbera theme for Jekyll inspired by Facebook's GraphQL documentation 
version:  2.0.0
author:   Greg Arakelian
email:    greg@arakelian.com

description: >
   A documentation theme for Jekyll Inspired by Facebook's <a href="http://graphql.org">GraphQL documentation</a>. 
   Made by <a href="https://github.com/arakelian">Greg Arakelian</a>.

    
# see: https://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title/

collections:
  learn:
    order: 1
    title: "Learn"
    output: true
  examples:
    order: 2
    title: "Examples"
    output: true
  posts:
    order: 3
    title: "Blog"
    indexPage: "/blog/"
    permalink:    /blog/:categories/:year/:month/:day/:title
